project_id = "udnxnhvzowsjawpvfjuq"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.handle-email-events]
    verify_jwt = false
  [functions.send-invitation-email]
    verify_jwt = true
  [functions.send-supplier-invitation-email]
    verify_jwt = true
  [functions.send-donation-receipt-email]
    verify_jwt = true
  [functions.register-supplier]
    verify_jwt = false
  [functions.billing-cron]
    verify_jwt = true
  [functions.yoco-charge-subscription]
    verify_jwt = true
  [functions.submit-contact]
    verify_jwt = false
