// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated." }],
    isError: true
  };
}

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's profile: name, email, department, role and organization.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile, error: pErr }, { data: roleRow }] = await Promise.all([
      sb.from("profiles").select("id,email,name,surname,department,organization_id,tier").eq("id", userId).maybeSingle(),
      sb.from("user_roles").select("role").eq("user_id", userId).maybeSingle()
    ]);
    if (pErr) return { content: [{ type: "text", text: pErr.message }], isError: true };
    const result = { ...profile, role: roleRow?.role ?? null };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-purchase-requisitions.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var list_purchase_requisitions_default = defineTool2({
  name: "list_purchase_requisitions",
  title: "List purchase requisitions",
  description: "List purchase requisitions visible to the signed-in user (scoped by access rules). Optionally filter by status and limit results.",
  inputSchema: {
    status: z.enum(["PENDING", "APPROVED", "REJECTED", "PAID", "IN_PROGRESS"]).optional().describe("Filter by requisition status."),
    limit: z.number().int().min(1).max(50).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    let q = sb.from("purchase_requisitions").select(
      "id,transaction_id,requested_by_name,requested_by_department,total_amount,currency,urgency,hod_status,finance_status,status,due_date,created_at"
    ).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { requisitions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-purchase-requisition.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_purchase_requisition_default = defineTool3({
  name: "get_purchase_requisition",
  title: "Get purchase requisition",
  description: "Fetch the full detail of a single purchase requisition by its transaction_id (e.g. PR-000123), including line items and approval history.",
  inputSchema: {
    transaction_id: z2.string().trim().min(1).describe("The requisition transaction_id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ transaction_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("purchase_requisitions").select("*").eq("transaction_id", transaction_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: `No requisition found for ${transaction_id}.` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { requisition: data }
    };
  }
});

// src/lib/mcp/tools/list-suppliers.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_suppliers_default = defineTool4({
  name: "list_suppliers",
  title: "List suppliers",
  description: "List suppliers visible to the signed-in user's organization (scoped by access rules). Optionally filter by a company-name search term.",
  inputSchema: {
    search: z3.string().trim().optional().describe("Case-insensitive company-name filter."),
    limit: z3.number().int().min(1).max(50).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    let q = sb.from("suppliers").select("id,company_name,contact_person,contact_email,phone,industry,is_verified,vat_number,created_at").order("company_name", { ascending: true }).limit(limit ?? 20);
    if (search) q = q.ilike("company_name", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { suppliers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-notifications.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_notifications_default = defineTool5({
  name: "list_notifications",
  title: "List notifications",
  description: "List the signed-in user's most recent notifications. Optionally show only unread ones.",
  inputSchema: {
    unread_only: z4.boolean().optional().describe("Only return unread notifications."),
    limit: z4.number().int().min(1).max(50).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ unread_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    let q = sb.from("notifications").select("id,title,message,type,is_read,created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (unread_only) q = q.eq("is_read", false);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { notifications: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "udnxnhvzowsjawpvfjuq";
var mcp_default = defineMcp({
  name: "ovasyt-mcp",
  title: "Ovasyt Procurement MCP",
  version: "0.1.0",
  instructions: "Tools for the Ovasyt procurement platform. Use `whoami` to identify the signed-in user, `list_purchase_requisitions` and `get_purchase_requisition` to inspect requisitions, `list_suppliers` to browse suppliers, and `list_notifications` for the user's alerts. All data is scoped to the signed-in user's access.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_purchase_requisitions_default,
    get_purchase_requisition_default,
    list_suppliers_default,
    list_notifications_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
